### ISSUE TITLE
Plugin fails to compile.

### ISSUE THREAD

**Issue by KateReller** [Dastan21/BDAddons#104]
`[Astra][PluginSubmanager][BetterDiscord] Failed to compile FavoriteMedia! 
TypeError: Cannot read property 'roleCircle' of undefined
    at plugin (C:\Users\Mary Spencer\Apps\Astra\plugins\BetterDiscord\FavoriteMedia.plugin.js:239:36)
    at C:\Users\Mary Spencer\Apps\Astra\plugins\BetterDiscord\FavoriteMedia.plugin.js:4731:10
    at C:\Users\Mary Spencer\Apps\Astra\plugins\BetterDiscord\FavoriteMedia.plugin.js:4732:4
    at Object.<anonymous> (C:\Users\Mary Spencer\Apps\Astra\plugins\BetterDiscord\FavoriteMedia.plugin.js:4733:3)
    at Object.<anonymous> (C:\Users\Mary Spencer\Apps\Astra\plugins\BetterDiscord\FavoriteMedia.plugin.js:4754:3)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Module._compile (C:\Users\Mary Spencer\Apps\Astra\src\manager\plugins\BetterDiscord\index.tsx:215:20)
    at Module._compile (C:\Users\Mary Spencer\Apps\Astra\src\manager\plugins\BetterDiscord\index.tsx:118:22)
    at Module._compile (C:\Users\Mary Spencer\Apps\Astra\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1108:10)`

**Comment by Dastan21** [comment]
https://github.com/Dastan21/BDAddons/issues/95#issuecomment-1181626100
