### ISSUE TITLE
Plugin could not be compiled

### ISSUE THREAD

**Issue by mcshept** [Dastan21/BDAddons#119]
TypeError: Cannot read property 'locale' of undefined

at setLabelsByLanguage (betterdiscord://plugins/FavoriteMedia.plugin.js:2020:31)
at plugin (betterdiscord://plugins/FavoriteMedia.plugin.js:306:19)
at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4512:10)
at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4513:4)
at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4514:3)
at Object.requireAddon (<anonymous>:4:43095)
at Object.loadAddon (<anonymous>:4:8859)
at Object.loadAddon (<anonymous>:4:40847)
at Object.loadAllAddons (<anonymous>:4:11269)
at Object.initialize (<anonymous>:4:5963)
at Object.initialize (<anonymous>:4:40050)
at Object.startup (<anonymous>:4:374950)

**Comment by Dastan21** [comment]
What's the plugin version ?

**Comment by Dylsxeic** [comment]
Hijacking this since I have the same issue. Version 1.6.2

TypeError: Cannot read property 'locale' of undefined
    at setLabelsByLanguage (betterdiscord://plugins/FavoriteMedia.plugin.js:2057:31)
    at plugin (betterdiscord://plugins/FavoriteMedia.plugin.js:312:19)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4733:10)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4734:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4735:3)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)

**Comment by Dastan21** [comment]
The latest version is 1.5.27, download from here (right-click, save as): https://raw.githubusercontent.com/Dastan21/BDAddons/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js

**Comment by Dylsxeic** [comment]
Seems to have corrected it! Thanks Dastan!
