### ISSUE TITLE
[FavoriteMedia]: Could not be compiled

### ISSUE THREAD

**Issue by sponnify** [Dastan21/BDAddons#134]
### Discord Build

Stable

### Discord Version

156540 (16ecd97)

### Plugin Version

Latest

### Steps To Reproduce

Attempt to install the plugin.

### Describe the bug

TypeError: Cannot read property 'ComponentDispatch' of undefined
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:343:75)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4592:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4593:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by Dastan21** [comment]
Duplicate of #131
