### ISSUE TITLE
[FavoriteMedia]: FM still won't work after trying out the solution in Issue #154

### ISSUE THREAD

**Issue by ronfino** [Dastan21/BDAddons#156]
### Discord Build

Stable

### Discord Version

Stable 164048 (25cf192)

### Plugin Version

1.6.2

### Steps To Reproduce

1. Start Discord
2. Get error.

### Describe the bug

When BD attempts to compile FavoriteMedia it fails and shows this error.
```
TypeError: Cannot read property 'item' of undefined
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:242:30)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4592:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4593:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)
```

### Screenshots

![image](https://user-images.githubusercontent.com/77462428/207733174-cb6196be-7b60-4582-b0c3-714c3ee6573c.png)

**Comment by Dastan21** [comment]
See this https://github.com/Dastan21/BDAddons/issues/151#issuecomment-1336533733

**Comment by ronfino** [comment]
Works, thanks! 

By the way, i suggest changing the download file from the BD page then, since i also attempted to fix it by copy-pasting a brand new file and it still gave me the same code error.
> You would get the latest plugin version [here](https://raw.githubusercontent.com/Dastan21/BDAddons/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

**Comment by Dastan21** [comment]
I'm not the one who decides the version on the website. BD mods validate each change, which can take some time.
