### ISSUE TITLE
[FavoriteMedia]: error

### ISSUE THREAD

**Issue by Sodz1aX** [Dastan21/BDAddons#158]
### Discord Build

Stable

### Discord Version

164355

### Plugin Version

1.6.2

### Steps To Reproduce

1. Launch discord
2. Error report

### Describe the bug

TypeError: Cannot read property 'item' of undefined
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:242:30)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4592:4)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:4593:3)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by Dastan21** [comment]
Duplicate #141
