### ISSUE TITLE
[FavoriteMedia]: Could not be compiled

### ISSUE THREAD

**Issue by dragonunitedtm** [Dastan21/BDAddons#220]
### Discord Build

Stable

### Discord Version

31c628d

### Plugin Version

1.8.7

### Steps To Reproduce

boot up discord

### Describe the bug

[bug.txt](https://github.com/Dastan21/BDAddons/files/12612044/bug.txt)

**Comment by Silvia-Dragoness** [comment]
Yep, error on discord startup (or reload):  Favorite Media could not be compiled.

Build:  stable
Version:  227949 (31c628d)
Plugin ver:  1.8.7

Full error text:
`TypeError: Cannot read properties of undefined (reading 'icon')
    at plugin (betterdiscord://plugins/FavoriteMedia.plugin.js:370:31)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:5614:13)
    at eval (betterdiscord://plugins/FavoriteMedia.plugin.js:5615:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at M.loadAllAddons (betterdiscord/renderer.js:4:10795)
    at M.initialize (betterdiscord/renderer.js:4:5219)
    at M.initialize (betterdiscord/renderer.js:4:32689)
    at Object.startup (betterdiscord/renderer.js:4:359757)`

Screenshots:
![image](https://github.com/Dastan21/BDAddons/assets/98713909/7db3b28b-307f-4e95-bf6a-70170c69bb9e)
![image](https://github.com/Dastan21/BDAddons/assets/98713909/5d9a427c-6568-4059-9b32-da67100d6a9a)

**Comment by Dastan21** [comment]
Fixed in v1.8.8
