### ISSUE TITLE
an error with powercord

### ISSUE THREAD

**Issue by KaizerFox** [Dastan21/BDAddons#24]
TypeError: Cannot read property 'addEventListener' of undefined
    at new Tooltip (\src\Powercord\plugins\bdCompat\plugins\0PluginLibrary.plugin.js:8880:19)
    at Function.create (\src\Powercord\plugins\bdCompat\plugins\0PluginLibrary.plugin.js:8891:53)
    at MediaFavButton.componentDidMount (\src\Powercord\plugins\bdCompat\plugins\FavoriteMedia.plugin.js:376:32) 
Component stack:

**Comment by Dastan21** [comment]
Then use BetterDiscord 😉
