### ISSUE TITLE
[FavoriteMedia]: Crash when opening any chat

### ISSUE THREAD

**Issue by romanin-rf** [Dastan21/BDAddons#276]
### Discord Build

Stable

### Discord Version

stable 342968 (f8fde36)

### Plugin Version

1.10.4

### Steps To Reproduce

1. Opening any chat.
2. Discord crash ;3

### Describe the bug

```
[2024-11-08 12:56:05.808][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.816][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.817][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.818][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.819][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.820][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.821][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.822][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.823][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.824][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.825][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:05.826][CONSOLE:ERROR] Cannot read properties of undefined (reading 'Messages')
TypeError: Cannot read properties of undefined (reading 'Messages')
    at MediaFavButton.componentDidMount (betterdiscord://plugins/FavoriteMedia.plugin.js:1017:141)
    at sX (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1028028)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048602)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048498)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1048613
    at oB (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1049125)
    at oy (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1032474)
    at T (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230240)
    at D (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1230770)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752248
    at O (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752013)
    at MessagePort.L (https://discord.com/assets/web.4b0befdc464a044c775e.js:1:752072)
[2024-11-08 12:56:06.742][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
Error: Menu API only allows Items and groups of Items as children. Received function g(e){return null} (object) instead
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2551475
    at Array.reduce (<anonymous>)
    at e (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2550263)
    at v (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:2551684)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:3012:21)
    at ah (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:995893)
    at l (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1053577)
    at oU (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036572)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036438
    at ok (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1036446)
    at oR (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1033531)
    at r6 (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:982257)
    at oD (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1034035)
    at https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1062122
    at lo (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1062152)
    at e.995340.t.render (https://discord.com/assets/web.4b0befdc464a044c775e.js:12:1065848)
    at MyReact.render (betterdiscord://plugins/0BDFDB.plugin.js:2996:40)
    at MyReact.hookCall (betterdiscord://plugins/0BDFDB.plugin.js:3011:23)
    at loadLibrary (betterdiscord://plugins/0BDFDB.plugin.js:8018:60)
    at parseData (betterdiscord://plugins/0BDFDB.plugin.js:1206:24)
    at parseCSS (betterdiscord://plugins/0BDFDB.plugin.js:1167:122)
    at requestLibraryData (betterdiscord://plugins/0BDFDB.plugin.js:1211:51)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1157:7)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:222:56)
```

### Screenshots

no.

**Comment by Infinitay** [comment]
@romanin-rf I had the same issue, and I found out today that it was in fact fixed. For some reason my BetterDiscord wasn't auto-updating it, so I never knew that it fixed until I updated manually. I fixed it by updating to the current latest (1.11.1) the issue went away for me. Replace your FavoriteMedia.plugin.js with the current latest version: https://raw.githubusercontent.com/Dastan21/BDAddons/refs/heads/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js

Try that out and see if it fixes for you too. I'm not sure if he implemented a workaround and Zeres is still broken or not, but I guess the following commit specifically fixed this specific issue https://github.com/Dastan21/BDAddons/commit/9bdb55b6baf56f6058e0b265f7f8e73d9ffefc7b
